Added Contributing.md
quellus/GDTuber pull request #109
Opened 2024-08-04 02:20 UTC by Thefunguy-Github

added the changes @quellus wanted

2024-08-04 17:31 UTC, quellus requested changes
You shouldn't have to make a new Pull Request each time. If you add new commits to the same branch, it will update this Pull Request

2024-08-04 17:31 UTC, quellus commented on wiki/Contributing.md
> +### Guidlines
```suggestion
### Guidelines
```

2024-08-04 17:31 UTC, quellus commented on wiki/Contributing.md
> +### Aditional Ntoes
```suggestion
### Additional Notes
```

2024-08-04 17:31 UTC, quellus commented on wiki/Contributing.md
> +> git clone https://github.com/quellus/GDTuber.git
For all of these block quotes, please change them to the code block format we have in the README

 ```sh
git clone https://github.com/quellus/GDTuber.git

2024-08-04 17:31 UTC, quellus commented on wiki/Contributing.md
> +5. Click 'Create pull request' and fill out the required information.
The numbering gets a little weird with this one. I think we need to tab these over to make it work right

```suggestion
  1. Go to the [GDTuber](https://github.com/quellus/GDTuber/) repository.
  2. Click on the 'Pull requests' tab.
  3. Click the 'New pull request' button.
  4. Select the branch you pushed your changes to in your forked repository.
  5. Click 'Create pull request' and fill out the required information.
```

2024-08-04 17:31 UTC, quellus commented on wiki/Contributing.md
> +- Keep discussions focused and on topic.
```suggestion
- Keep discussions focused and on topic.

Thank you for your contributions!

For any questions or additional help, feel free to open an issue or contact us on our [Discord server](https://discord.com/invite/RzaVWjPU8s).
```

2024-08-04 17:47 UTC, quellus commented
Closes #104

2024-08-08 20:30 UTC, quellus commented
@dohro-github Is there any way we can help get this merged?

2024-08-10 15:51 UTC, dohro-github commented
> @dohro-github Is there any way we can help get this merged?

I think you can just fix the errors in my md code then merge it, if that is what you are asking

2024-08-11 20:15 UTC, merged