save load system
quellus/GDTuber pull request #26
Opened 2024-07-06 09:52 UTC by M-125

ur "art" will be saved when clicking the quit button
all u have to do is to trigger load() method of a layoutsaver node (probably from main menu) to load /create canvas to put sprites on

2024-07-06 09:53 UTC, M-125 commented
saving happens on pressing quit button and doesnt need another layoutsaver node
(static func)

2024-07-06 16:45 UTC, quellus requested changes
I want to get this working with the main scene `MicRecord.tscn` before we merge.
It seems like we either need to add the save script somewhere in the scene or make it an autoload since the `load()` function can't be made static.

2024-07-06 16:45 UTC, quellus commented on scripts/Menu.gd
> +	print("req")
```suggestion

```

2024-07-06 16:45 UTC, quellus commented on scenes/MicRecord.tscn
> +ok_button_text = "Megnyitás"
```suggestion
ok_button_text = "Open"
```

2024-07-06 16:45 UTC, quellus commented on scripts/save.gd
Rename `save.gd` to `layout_saver.gd` so it has the same name as the class.

2024-07-06 16:46 UTC, quellus commented
Closes #26

2024-07-07 07:08 UTC, M-125 commented
What did i forget to do that this still cant be merged

2024-07-10 20:49 UTC, closed without merging